use crate::telemetry::SessionMetrics;
use serde_json::{Map, Value, json};

use super::put;

pub(super) fn put_guidance_fields(session_json: &mut Map<String, Value>, session: &SessionMetrics) {
    put(
        session_json,
        "truncated_response_count",
        json!(session.truncation.truncated_response_count),
    );
    put(
        session_json,
        "truncation_followup_count",
        json!(session.truncation.truncation_followup_count),
    );
    put(
        session_json,
        "truncation_same_tool_retry_count",
        json!(session.truncation.truncation_same_tool_retry_count),
    );
    put(
        session_json,
        "truncation_handle_followup_count",
        json!(session.truncation.truncation_handle_followup_count),
    );
    put(
        session_json,
        "handle_reuse_count",
        json!(session.truncation.handle_reuse_count),
    );
    put(
        session_json,
        "repeated_low_level_chain_count",
        json!(session.guidance.repeated_low_level_chain_count),
    );
    put(
        session_json,
        "composite_guidance_emitted_count",
        json!(session.guidance.composite_guidance_emitted_count),
    );
    put(
        session_json,
        "composite_guidance_followed_count",
        json!(session.guidance.composite_guidance_followed_count),
    );
    put(
        session_json,
        "composite_guidance_missed_count",
        json!(session.guidance.composite_guidance_missed_count),
    );
    put(
        session_json,
        "composite_guidance_missed_by_origin",
        json!(session.guidance.composite_guidance_missed_by_origin),
    );
    put(
        session_json,
        "quality_contract_emitted_count",
        json!(session.guidance.quality_contract_emitted_count),
    );
    put(
        session_json,
        "recommended_checks_emitted_count",
        json!(session.guidance.recommended_checks_emitted_count),
    );
    put(
        session_json,
        "recommended_check_followthrough_count",
        json!(session.guidance.recommended_check_followthrough_count),
    );
    put(
        session_json,
        "quality_focus_reuse_count",
        json!(session.guidance.quality_focus_reuse_count),
    );
    put(
        session_json,
        "performance_watchpoint_emit_count",
        json!(session.guidance.performance_watchpoint_emit_count),
    );
    put(
        session_json,
        "verifier_contract_emitted_count",
        json!(session.guidance.verifier_contract_emitted_count),
    );
    put(
        session_json,
        "blocker_emit_count",
        json!(session.guidance.blocker_emit_count),
    );
    put(
        session_json,
        "verifier_followthrough_count",
        json!(session.guidance.verifier_followthrough_count),
    );
    put(
        session_json,
        "coordination_registration_count",
        json!(session.coordination.coordination_registration_count),
    );
    put(
        session_json,
        "coordination_claim_count",
        json!(session.coordination.coordination_claim_count),
    );
    put(
        session_json,
        "coordination_release_count",
        json!(session.coordination.coordination_release_count),
    );
    put(
        session_json,
        "coordination_overlap_emit_count",
        json!(session.coordination.coordination_overlap_emit_count),
    );
    put(
        session_json,
        "coordination_caution_emit_count",
        json!(session.coordination.coordination_caution_emit_count),
    );
    put(
        session_json,
        "mutation_preflight_checked_count",
        json!(session.mutation.mutation_preflight_checked_count),
    );
    put(
        session_json,
        "mutation_without_preflight_count",
        json!(session.mutation.mutation_without_preflight_count),
    );
    put(
        session_json,
        "mutation_preflight_gate_denied_count",
        json!(session.mutation.mutation_preflight_gate_denied_count),
    );
    put(
        session_json,
        "stale_preflight_reject_count",
        json!(session.mutation.stale_preflight_reject_count),
    );
    put(
        session_json,
        "mutation_with_caution_count",
        json!(session.mutation.mutation_with_caution_count),
    );
    put(
        session_json,
        "rename_without_symbol_preflight_count",
        json!(session.mutation.rename_without_symbol_preflight_count),
    );
    put(
        session_json,
        "deferred_namespace_expansion_count",
        json!(session.namespace.deferred_namespace_expansion_count),
    );
    put(
        session_json,
        "deferred_hidden_tool_call_denied_count",
        json!(session.namespace.deferred_hidden_tool_call_denied_count),
    );
    put(
        session_json,
        "profile_switch_count",
        json!(session.namespace.profile_switch_count),
    );
    put(
        session_json,
        "preset_switch_count",
        json!(session.namespace.preset_switch_count),
    );
    put(
        session_json,
        "composite_calls",
        json!(session.call_type.composite_calls),
    );
    put(
        session_json,
        "low_level_calls",
        json!(session.call_type.low_level_calls),
    );
    put(
        session_json,
        "stdio_session_count",
        json!(session.transport.stdio_session_count),
    );
    put(
        session_json,
        "http_session_count",
        json!(session.transport.http_session_count),
    );
}
