use super::{SessionFieldInputs, put};
use serde_json::{Map, Value, json};

pub(super) fn put_ops_fields(
    session_json: &mut Map<String, Value>,
    inputs: &SessionFieldInputs<'_>,
) {
    let session = inputs.session;
    put(
        session_json,
        "analysis_jobs_enqueued",
        json!(session.jobs.analysis_jobs_enqueued),
    );
    put(
        session_json,
        "analysis_jobs_started",
        json!(session.jobs.analysis_jobs_started),
    );
    put(
        session_json,
        "analysis_jobs_completed",
        json!(session.jobs.analysis_jobs_completed),
    );
    put(
        session_json,
        "analysis_jobs_failed",
        json!(session.jobs.analysis_jobs_failed),
    );
    put(
        session_json,
        "analysis_jobs_cancelled",
        json!(session.jobs.analysis_jobs_cancelled),
    );
    put(
        session_json,
        "analysis_queue_depth",
        json!(session.jobs.analysis_queue_depth),
    );
    put(
        session_json,
        "analysis_queue_max_depth",
        json!(session.jobs.analysis_queue_max_depth),
    );
    put(
        session_json,
        "analysis_queue_weighted_depth",
        json!(session.jobs.analysis_queue_weighted_depth),
    );
    put(
        session_json,
        "analysis_queue_max_weighted_depth",
        json!(session.jobs.analysis_queue_max_weighted_depth),
    );
    put(
        session_json,
        "analysis_queue_priority_promotions",
        json!(session.jobs.analysis_queue_priority_promotions),
    );
    put(
        session_json,
        "active_analysis_workers",
        json!(session.jobs.active_analysis_workers),
    );
    put(
        session_json,
        "peak_active_analysis_workers",
        json!(session.jobs.peak_active_analysis_workers),
    );
    put(
        session_json,
        "analysis_worker_limit",
        json!(session.jobs.analysis_worker_limit),
    );
    put(
        session_json,
        "analysis_cost_budget",
        json!(session.jobs.analysis_cost_budget),
    );
    put(
        session_json,
        "analysis_transport_mode",
        json!(session.jobs.analysis_transport_mode.clone()),
    );
    put(session_json, "daemon_mode", json!(inputs.daemon_mode));
    put(
        session_json,
        "watcher_running",
        json!(
            inputs
                .watcher_stats
                .map(|stats| stats.running)
                .unwrap_or(false)
        ),
    );
    put(
        session_json,
        "watcher_events_processed",
        json!(
            inputs
                .watcher_stats
                .map(|stats| stats.events_processed)
                .unwrap_or(0)
        ),
    );
    put(
        session_json,
        "watcher_files_reindexed",
        json!(
            inputs
                .watcher_stats
                .map(|stats| stats.files_reindexed)
                .unwrap_or(0)
        ),
    );
    put(
        session_json,
        "watcher_lock_contention_batches",
        json!(
            inputs
                .watcher_stats
                .map(|stats| stats.lock_contention_batches)
                .unwrap_or(0)
        ),
    );
    put(
        session_json,
        "watcher_index_failures",
        json!(inputs.watcher_failure_health.recent_failures),
    );
    put(
        session_json,
        "watcher_index_failures_total",
        json!(inputs.watcher_failure_health.total_failures),
    );
    put(
        session_json,
        "watcher_stale_index_failures",
        json!(inputs.watcher_failure_health.stale_failures),
    );
    put(
        session_json,
        "watcher_persistent_index_failures",
        json!(inputs.watcher_failure_health.persistent_failures),
    );
    put(
        session_json,
        "watcher_pruned_missing_failures",
        json!(inputs.watcher_failure_health.pruned_missing_failures),
    );
    put(
        session_json,
        "watcher_recent_failure_window_seconds",
        json!(inputs.watcher_failure_health.recent_window_seconds),
    );
    put(
        session_json,
        "avg_ms_per_call",
        json!(
            session
                .core
                .total_ms
                .checked_div(session.core.total_calls)
                .unwrap_or(0)
        ),
    );
    put(
        session_json,
        "avg_tool_output_tokens",
        json!(if session.core.total_calls > 0 {
            session.core.total_tokens / session.core.total_calls as usize
        } else {
            0
        }),
    );
    put(
        session_json,
        "p50_tool_latency_ms",
        json!(crate::telemetry::percentile_50(
            &session.core.latency_samples
        )),
    );
    put(
        session_json,
        "p95_tool_latency_ms",
        json!(crate::telemetry::percentile_95(
            &session.core.latency_samples
        )),
    );
    put(
        session_json,
        "timeline_length",
        json!(session.timeline.len()),
    );
}
