use super::super::{ToolPreset, ToolProfile};

pub(crate) const MINIMAL_TOOLS: &[&str] = &[
    "activate_project",
    "prepare_harness_session",
    "register_agent_work",
    "list_active_agents",
    "claim_files",
    "release_files",
    "get_current_config",
    "set_preset",
    "set_profile",
    "read_file",
    "list_dir",
    "find_file",
    "search_for_pattern",
    "get_symbols_overview",
    "find_symbol",
    "get_ranked_context",
    "find_referencing_symbols",
    "get_type_hierarchy",
    "refresh_symbol_index",
    "get_file_diagnostics",
    "search_workspace_symbols",
    "plan_symbol_rename",
    "rename_symbol",
    "replace_symbol_body",
    "insert_content",
    "create_text_file",
    "replace",
];

pub(crate) const BALANCED_EXCLUDES: &[&str] = &[
    "find_circular_dependencies",
    "get_change_coupling",
    "get_symbol_importance",
    "find_dead_code",
    "refactor_extract_function",
    "refactor_inline_function",
    "refactor_move_to_file",
    "refactor_change_signature",
    "get_complexity",
    "search_symbols_fuzzy",
    "check_lsp_status",
    "get_lsp_recipe",
    "read_file",
    "list_dir",
    "find_file",
    "search_for_pattern",
    "prepare_for_new_conversation",
    "get_watch_status",
    "prune_index_failures",
    "get_tool_metrics",
    "audit_builder_session",
    "audit_planner_session",
    "export_session_markdown",
    "export_session_markdown",
    "summarize_changes",
    "summarize_file",
    "insert_at_line",
    "insert_before_symbol",
    "insert_after_symbol",
    "replace_lines",
    "get_project_structure",
];

pub(crate) const PLANNER_READONLY_TOOLS: &[&str] = &[
    "activate_project",
    "prepare_harness_session",
    "register_agent_work",
    "list_active_agents",
    "claim_files",
    "release_files",
    "get_current_config",
    "get_capabilities",
    "set_profile",
    "set_preset",
    "get_tool_metrics",
    "audit_builder_session",
    "audit_planner_session",
    "explore_codebase",
    "review_architecture",
    "plan_safe_refactor",
    "review_changes",
    "diagnose_issues",
    "find_symbol",
    "get_symbols_overview",
    "get_ranked_context",
    "find_referencing_symbols",
    "semantic_search",
    "index_embeddings",
    "get_impact_analysis",
    "get_changed_files",
    "onboard_project",
    "analyze_change_request",
    "verify_change_readiness",
    "find_minimal_context_for_change",
    "impact_report",
    "mermaid_module_graph",
    "start_analysis_job",
    "get_analysis_job",
    "get_analysis_section",
    "get_lsp_readiness",
];

pub(crate) const BUILDER_MINIMAL_TOOLS: &[&str] = &[
    "activate_project",
    "prepare_harness_session",
    "register_agent_work",
    "list_active_agents",
    "claim_files",
    "release_files",
    "get_current_config",
    "get_capabilities",
    "set_profile",
    "set_preset",
    "get_tool_metrics",
    "audit_builder_session",
    "audit_planner_session",
    "export_session_markdown",
    "explore_codebase",
    "trace_request_path",
    "plan_safe_refactor",
    "find_symbol",
    "get_symbols_overview",
    "get_ranked_context",
    "find_referencing_symbols",
    "get_file_diagnostics",
    "get_lsp_readiness",
    "find_tests",
    "refresh_symbol_index",
    "semantic_search",
    "index_embeddings",
    "plan_symbol_rename",
    "rename_symbol",
    "replace_symbol_body",
    "insert_content",
    "replace",
    "create_text_file",
    "analyze_missing_imports",
    "add_import",
    "find_minimal_context_for_change",
    "verify_change_readiness",
];

pub(crate) const REVIEWER_GRAPH_PRIMARY_TOOLS: &[&str] = &[
    "find_symbol",
    "find_referencing_symbols",
    "get_symbols_overview",
    "get_ranked_context",
    "impact_report",
    "review_changes",
    "review_architecture",
    "verify_change_readiness",
    "prepare_harness_session",
    "get_analysis_section",
    "get_file_diagnostics",
    "tool_search",
];

pub(crate) const REVIEWER_GRAPH_TOOLS: &[&str] = &[
    "activate_project",
    "prepare_harness_session",
    "register_agent_work",
    "list_active_agents",
    "claim_files",
    "release_files",
    "get_current_config",
    "set_profile",
    "set_preset",
    "audit_builder_session",
    "audit_planner_session",
    "export_session_markdown",
    "review_architecture",
    "cleanup_duplicate_logic",
    "review_changes",
    "diagnose_issues",
    "find_symbol",
    "get_symbols_overview",
    "get_ranked_context",
    "find_referencing_symbols",
    "find_scoped_references",
    "get_file_diagnostics",
    "get_lsp_readiness",
    "get_impact_analysis",
    "get_changed_files",
    "impact_report",
    "refactor_safety_report",
    "verify_change_readiness",
    "summarize_symbol_impact",
    "diff_aware_references",
    "semantic_code_review",
    "module_boundary_report",
    "mermaid_module_graph",
    "start_analysis_job",
    "get_analysis_job",
    "get_analysis_section",
    "tool_search",
];

pub(crate) const REFACTOR_FULL_TOOLS: &[&str] = &[
    "activate_project",
    "prepare_harness_session",
    "register_agent_work",
    "list_active_agents",
    "claim_files",
    "release_files",
    "get_current_config",
    "set_profile",
    "set_preset",
    "get_tool_metrics",
    "audit_builder_session",
    "audit_planner_session",
    "export_session_markdown",
    "explore_codebase",
    "trace_request_path",
    "review_architecture",
    "plan_safe_refactor",
    "review_changes",
    "diagnose_issues",
    "find_symbol",
    "get_symbols_overview",
    "get_ranked_context",
    "find_referencing_symbols",
    "find_scoped_references",
    "get_file_diagnostics",
    "get_lsp_readiness",
    "get_impact_analysis",
    "get_changed_files",
    "plan_symbol_rename",
    "rename_symbol",
    "replace_symbol_body",
    "insert_content",
    "replace",
    "create_text_file",
    "analyze_missing_imports",
    "add_import",
    "refactor_extract_function",
    "refactor_inline_function",
    "refactor_move_to_file",
    "refactor_change_signature",
    "refactor_safety_report",
    "safe_rename_report",
    "unresolved_reference_check",
    "verify_change_readiness",
    "impact_report",
    "diff_aware_references",
    "replace_content",
    "start_analysis_job",
    "get_analysis_job",
    "get_analysis_section",
];

pub(crate) const CI_AUDIT_TOOLS: &[&str] = &[
    "activate_project",
    "prepare_harness_session",
    "register_agent_work",
    "list_active_agents",
    "claim_files",
    "release_files",
    "get_current_config",
    "get_capabilities",
    "set_profile",
    "set_preset",
    "get_tool_metrics",
    "audit_builder_session",
    "audit_planner_session",
    "export_session_markdown",
    "explore_codebase",
    "review_architecture",
    "cleanup_duplicate_logic",
    "review_changes",
    "diagnose_issues",
    "read_file",
    "search_for_pattern",
    "find_tests",
    "get_symbols_overview",
    "find_symbol",
    "get_ranked_context",
    "get_changed_files",
    "get_impact_analysis",
    "find_scoped_references",
    "find_dead_code",
    "find_circular_dependencies",
    "get_change_coupling",
    "analyze_change_request",
    "verify_change_readiness",
    "summarize_symbol_impact",
    "unresolved_reference_check",
    "module_boundary_report",
    "dead_code_report",
    "impact_report",
    "refactor_safety_report",
    "diff_aware_references",
    "start_analysis_job",
    "get_analysis_job",
    "get_analysis_section",
];

pub(crate) const WORKFLOW_FIRST_TOOLS: &[&str] = &[
    "activate_project",
    "register_agent_work",
    "list_active_agents",
    "claim_files",
    "release_files",
    "get_current_config",
    "set_preset",
    "set_profile",
    "audit_planner_session",
    "export_session_markdown",
    "explore_codebase",
    "trace_request_path",
    "review_architecture",
    "plan_safe_refactor",
    "cleanup_duplicate_logic",
    "review_changes",
    "diagnose_issues",
    "analyze_change_request",
    "onboard_project",
];

pub(crate) const EVALUATOR_COMPACT_TOOLS: &[&str] = &[
    "activate_project",
    "prepare_harness_session",
    "get_current_config",
    "get_capabilities",
    "set_profile",
    "set_preset",
    "get_changed_files",
    "verify_change_readiness",
    "get_file_diagnostics",
    "find_tests",
    "read_file",
    "get_symbols_overview",
    "find_symbol",
    "get_analysis_section",
];

pub(crate) fn default_budget_for_preset(preset: ToolPreset) -> usize {
    match preset {
        ToolPreset::Minimal => 2000,
        ToolPreset::Balanced => 4000,
        ToolPreset::Full => 8000,
    }
}

pub(crate) fn default_budget_for_profile(profile: ToolProfile) -> usize {
    match profile {
        ToolProfile::PlannerReadonly => 2400,
        ToolProfile::BuilderMinimal => 2400,
        ToolProfile::ReviewerGraph => 2800,
        ToolProfile::EvaluatorCompact => 1600,
        ToolProfile::RefactorFull => 4000,
        ToolProfile::CiAudit => 3600,
        ToolProfile::WorkflowFirst => 2400,
    }
}
