#!/usr/bin/env python3
"""Regenerate tool definition Rust modules from `tools.toml`.

This is the codegen counterpart of ADR-0013. The single source of truth
is `crates/codelens-mcp/tools.toml`; the generated output lives next to
the hand-edited tool registry under
`crates/codelens-mcp/src/tool_defs/generated/`.

Usage:
    python3 scripts/regen-tool-defs.py --write   # rewrite generated files
    python3 scripts/regen-tool-defs.py --check   # exit 1 on drift, print hint

The migration is per-category (ADR-0013 §Decision §4). PR-A scaffolds
the file_io category only; subsequent PRs extend `tools.toml` and the
emit table below.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS_TOML = REPO_ROOT / "crates" / "codelens-mcp" / "tools.toml"
OUT_DIR = REPO_ROOT / "crates" / "codelens-mcp" / "src" / "tool_defs" / "generated"
BUILD_GEN = OUT_DIR / "build_generated.rs"
PRESETS_RS = REPO_ROOT / "crates" / "codelens-mcp" / "src" / "tool_defs" / "presets.rs"

SUPPORTED_SCHEMA = "v1"

# Maps the `preset_tags` token used in tools.toml to the Rust constant in
# `tool_defs/presets.rs` that should mirror its inversion. Drift between
# the two surfaces is a CI failure (see `validate_preset_tags`). #200
# stage 2 only validates equivalence; stage 3 will switch the Rust side
# to a codegen path so tools.toml becomes the single source.
PRESET_TAG_TO_CONST: dict[str, str] = {
    "minimal": "MINIMAL_TOOLS",
    "balanced-excluded": "BALANCED_EXCLUDES",
    "planner-readonly": "PLANNER_READONLY_TOOLS",
    "builder-minimal": "BUILDER_MINIMAL_TOOLS",
    "reviewer-graph": "REVIEWER_GRAPH_TOOLS",
}

# Map TOML `annotations` strings to the Rust local-variable name in
# `tool_defs/build.rs::build_tools`. Extend this table as new categories
# migrate; the category emit function only takes the bindings its tools
# actually reference (see `bindings_for_category` below).
ANNOTATION_BINDINGS: dict[str, str] = {
    "ro_p": "ro_p",
    "ro_a": "ro_a",
    "ro_w": "ro_w",
    "ro": "ro",
    "mut_p": "mut_p",
    "mut_w": "mut_w",
    "mutating": "mutating",
    "destructive": "destructive",
    "dest_a": "dest_a",
    # `mutating` flavour with audit_category="coordination" but no
    # approval_required — used by the multi-agent advisory tools
    # (register_agent_work, claim_files, release_files).
    "mut_coord": "mut_coord",
}

HEADER = """//! AUTO-GENERATED by `scripts/regen-tool-defs.py`. DO NOT EDIT.
//!
//! Source: `crates/codelens-mcp/tools.toml`
//! Run `python3 scripts/regen-tool-defs.py --write` to refresh.
//!
//! See `docs/adr/ADR-0013-tool-defs-codegen.md` for the migration plan.

#![allow(clippy::too_many_lines)]

use crate::protocol::{Tool, ToolAnnotations};
use crate::tool_defs::output_schemas::*;
use serde_json::json;
"""


def bindings_for_category(tools: list[dict[str, Any]]) -> list[str]:
    """Sorted unique annotation bindings used by a category's tools."""
    used = {tool.get("annotations", "ro_p") for tool in tools}
    for ann in used:
        if ann not in ANNOTATION_BINDINGS:
            raise SystemExit(
                f"annotations='{ann}' is not wired into regen-tool-defs.py. "
                "Extend ANNOTATION_BINDINGS first."
            )
    return sorted(used)


def render_tool(tool: dict[str, Any]) -> list[str]:
    name = tool["name"]
    desc = tool["description"]
    schema = tool["input_schema"]
    ann_key = tool.get("annotations", "ro_p")
    ann_var = ANNOTATION_BINDINGS[ann_key]
    schema_json = json.dumps(
        schema, separators=(",", ":"), sort_keys=False, ensure_ascii=False
    )

    builder_chain = []
    if "output_schema" in tool:
        builder_chain.append(f".with_output_schema({tool['output_schema']}())")
    builder_chain.append(f".with_annotations({ann_var}.clone())")
    if "max_response_tokens" in tool:
        builder_chain.append(
            f".with_max_response_tokens({int(tool['max_response_tokens'])})"
        )
    chain = "".join(builder_chain)

    return [
        "        Tool::new(",
        f"            {json.dumps(name, ensure_ascii=False)},",
        f"            {json.dumps(desc, ensure_ascii=False)},",
        f"            json!({schema_json}),",
        f"        ){chain},",
    ]


def category_feature_gate(tools: list[dict[str, Any]]) -> str | None:
    """Return the shared `feature_gate` if every tool agrees, else None.

    The codegen only supports an all-or-nothing feature gate per
    category — the calling convention in `build.rs` extends one Vec
    per category, so a mixed category would need per-Tool cfg
    attributes inside the vec, which the script does not emit. If a
    future PR needs a mixed category, update this function and the
    Tool::new emit path together.
    """
    gates = {tool.get("feature_gate") for tool in tools}
    if len(gates) > 1:
        raise SystemExit(
            f"tools in the same category disagree on feature_gate: {gates}. "
            "Split into separate categories."
        )
    return next(iter(gates))


def render_category(category: str, tools: list[dict[str, Any]]) -> str:
    bindings = bindings_for_category(tools)
    args = ", ".join(f"{ANNOTATION_BINDINGS[b]}: &ToolAnnotations" for b in bindings)
    # `pub` here is intentionally permissive at the function level; the
    # narrow `pub(super) use` re-export in `tool_defs/generated/mod.rs`
    # is what actually constrains visibility to `tool_defs`. See
    # ADR-0013 for the visibility model.
    lines: list[str] = []
    gate = category_feature_gate(tools)
    if gate is not None:
        lines.append(f'#[cfg(feature = "{gate}")]')
    lines.append(f"pub fn {category}_tools({args}) -> Vec<Tool> {{")
    lines.append("    vec![")
    for t in tools:
        lines.extend(render_tool(t))
    lines.append("    ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _strip_line_comments(src: str) -> str:
    """Drop `// ...` tails line-wise so quoted names inside comments
    (doc examples, commented-out registrations) never count as matches."""
    cleaned_lines: list[str] = []
    for line in src.split("\n"):
        idx = line.find("//")
        cleaned_lines.append(line if idx < 0 else line[:idx])
    return "\n".join(cleaned_lines)


def extract_preset_const(name: str, src: str) -> set[str]:
    """Return the &str literals inside `pub(crate) const <name>: &[&str] = &[ ... ];`.

    Strips `// ...` line comments from the body before extracting string
    literals — the constants contain prose rationale that would
    otherwise contribute false-positive matches.
    """
    pat = re.compile(
        rf"pub\(crate\) const {re.escape(name)}: &\[&str\] = &\[(.*?)\];",
        re.DOTALL,
    )
    m = pat.search(src)
    if not m:
        raise SystemExit(f"could not locate const {name} in presets.rs")
    cleaned = _strip_line_comments(m.group(1))
    return set(re.findall(r'"([^"]+)"', cleaned))


# ── Surface drift report + description lint ────────────────────────────
# PLAN_serena-alignment-p1 Phase 1 (#346). Warn-only until Phase 2
# resolves the known ghosts and flips on enforcement.

DISPATCH_SOURCES: tuple[Path, ...] = (
    REPO_ROOT / "crates" / "codelens-mcp" / "src" / "tools" / "mod.rs",
    REPO_ROOT / "crates" / "codelens-mcp" / "src" / "dispatch" / "table.rs",
)

# Dispatch-only names sanctioned while ADR-0009/D3 decides the symbolic
# edit core (spec 2026-06-10 §D3). Filled by Phase 2; empty means every
# dispatch-only name is reported as drift.
DISPATCH_ONLY_ALLOWLIST: frozenset[str] = frozenset()

# (tool, referenced_tool) description cross-references that are
# intentionally allowed. Keep empty unless a pairing is genuinely
# load-bearing; chaining belongs in suggested_next_tools (spec D7).
DESCRIPTION_XREF_ALLOWLIST: frozenset[tuple[str, str]] = frozenset()


def parse_dispatch_names(src: str) -> set[str]:
    """Extract tool names from dispatch-registration source text.

    Handles both registration styles in this repo:
      1. `tool_registry!` match arms — `"name" => module::handler,`
      2. handler-map inserts — `m.insert("name", std::sync::Arc::new(handler))`,
         including the rustfmt multi-line form. The `Arc::new` requirement
         keeps serde_json payload inserts inside handler bodies
         (`payload.insert("provenance", json!(..))`) from counting.
    """
    stripped = _strip_line_comments(src)
    names = set(re.findall(r'"([A-Za-z0-9_]+)"\s*=>', stripped))
    names |= set(
        re.findall(
            r'\.insert\(\s*"([A-Za-z0-9_]+)"\s*,\s*(?:std::sync::)?Arc::new',
            stripped,
        )
    )
    return names


def collect_dispatch_names() -> set[str]:
    """Union of dispatch names across all known registration sites."""
    names: set[str] = set()
    for path in DISPATCH_SOURCES:
        names |= parse_dispatch_names(path.read_text())
    return names


def three_way_report(
    dispatch: set[str],
    schema: set[str],
    preset_members: set[str],
    dispatch_only_allowlist: frozenset[str] | set[str] = frozenset(),
) -> dict[str, list[str]]:
    """Classify surface drift between the three registries.

    - dispatch_only: callable but schemaless — invisible to tools/list
    - allowlisted_dispatch_only: sanctioned pending-D3 exceptions
    - schema_only: listed but not dispatchable — dead schema
    - preset_dead: preset members without a tools.toml definition —
      strings the surface filter can never match
    """
    dispatch_only = dispatch - schema
    return {
        "dispatch_only": sorted(dispatch_only - set(dispatch_only_allowlist)),
        "allowlisted_dispatch_only": sorted(dispatch_only & set(dispatch_only_allowlist)),
        "schema_only": sorted(schema - dispatch),
        "preset_dead": sorted(preset_members - schema),
    }


def lint_description_crossrefs(
    tools: list[dict[str, Any]],
    allowlist: frozenset[tuple[str, str]] | set[tuple[str, str]] = DESCRIPTION_XREF_ALLOWLIST,
) -> list[str]:
    """Flag descriptions that reference other tools by name (spec D7).

    Tool-search surfaces retrieve descriptions independently; chaining
    guidance belongs in suggested_next_tools, not prose name-drops.
    Word-boundary match; self-references are fine.
    """
    names = {tool["name"] for tool in tools}
    offenses: list[str] = []
    for tool in tools:
        desc = tool.get("description", "") or ""
        for other in sorted(names - {tool["name"]}):
            if (tool["name"], other) in allowlist:
                continue
            if re.search(rf"\b{re.escape(other)}\b", desc):
                offenses.append(
                    f"{tool['name']}: description references tool `{other}` "
                    "(move chaining to suggested_next_tools — spec D7)"
                )
    return offenses


def surface_drift_warnings(tools: list[dict[str, Any]]) -> list[str]:
    """Assemble the live 3-way drift report + description lint lines."""
    schema_names = {tool["name"] for tool in tools}
    presets_src = PRESETS_RS.read_text()
    preset_members: set[str] = set()
    for const_name in PRESET_TAG_TO_CONST.values():
        preset_members |= extract_preset_const(const_name, presets_src)
    report = three_way_report(
        collect_dispatch_names(),
        schema_names,
        preset_members,
        dispatch_only_allowlist=DISPATCH_ONLY_ALLOWLIST,
    )
    lines: list[str] = []
    for key in ("dispatch_only", "schema_only", "preset_dead"):
        if report[key]:
            lines.append(f"{key} ({len(report[key])}): {', '.join(report[key])}")
    if report["allowlisted_dispatch_only"]:
        lines.append(
            "allowlisted_dispatch_only (pending-D3): "
            + ", ".join(report["allowlisted_dispatch_only"])
        )
    lines.extend(lint_description_crossrefs(tools))
    return lines


def validate_preset_tags(tools: list[dict[str, Any]]) -> list[str]:
    """Return human-readable mismatch lines between preset_tags and presets.rs.

    Inverts `[[tool]].preset_tags` into one set per preset tag. The Rust
    side holds the same data as five `pub(crate) const <NAME>: &[&str]`
    arrays in `tool_defs/presets.rs`. The two must agree **for tools
    that exist in tools.toml**. Members listed in presets.rs but absent
    from tools.toml ("orphans" — dead members `tools()` cannot surface)
    are reported by `surface_drift_warnings` as `preset_dead`.
    """
    src = PRESETS_RS.read_text()
    tools_in_toml = {tool["name"] for tool in tools}

    inverse: dict[str, set[str]] = {tag: set() for tag in PRESET_TAG_TO_CONST}
    for tool in tools:
        for tag in tool.get("preset_tags", []) or []:
            if tag in inverse:
                inverse[tag].add(tool["name"])

    mismatches: list[str] = []

    for tag, const_name in PRESET_TAG_TO_CONST.items():
        toml_set = inverse.get(tag, set())
        rs_set = extract_preset_const(const_name, src)
        rs_in_toml = rs_set & tools_in_toml
        only_toml = toml_set - rs_in_toml
        only_rs = rs_in_toml - toml_set
        if only_toml:
            mismatches.append(
                f"{const_name}: in tools.toml preset_tags but not in "
                f"presets.rs: {sorted(only_toml)}"
            )
        if only_rs:
            mismatches.append(
                f"{const_name}: in presets.rs but missing from "
                f"tools.toml preset_tags: {sorted(only_rs)}"
            )

    unknown_tags: set[str] = set()
    for tool in tools:
        for tag in tool.get("preset_tags", []) or []:
            if tag not in PRESET_TAG_TO_CONST:
                unknown_tags.add(tag)
    if unknown_tags:
        mismatches.append(
            f"unknown preset_tags values (not in PRESET_TAG_TO_CONST): "
            f"{sorted(unknown_tags)}"
        )
    return mismatches


def render() -> str:
    with TOOLS_TOML.open("rb") as f:
        data = tomllib.load(f)
    if data.get("schema_version") != SUPPORTED_SCHEMA:
        raise SystemExit(
            f"tools.toml schema_version='{data.get('schema_version')}' is not "
            f"supported by this script ({SUPPORTED_SCHEMA})"
        )
    by_category: dict[str, list[dict[str, Any]]] = {}
    for tool in data.get("tool", []):
        by_category.setdefault(tool["category"], []).append(tool)

    parts: list[str] = [HEADER]
    for category in sorted(by_category):
        parts.append("")
        parts.append(render_category(category, by_category[category]))
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="rewrite generated files")
    mode.add_argument("--check", action="store_true", help="exit 1 on drift")
    args = parser.parse_args()

    with TOOLS_TOML.open("rb") as f:
        toml_data = tomllib.load(f)
    preset_mismatches = validate_preset_tags(toml_data.get("tool", []))
    if preset_mismatches:
        print(
            "preset_tags drift between tools.toml and "
            "crates/codelens-mcp/src/tool_defs/presets.rs:",
            file=sys.stderr,
        )
        for line in preset_mismatches:
            print(f"  - {line}", file=sys.stderr)
        print(
            "edit tools.toml preset_tags or presets.rs constants so they "
            "agree, then re-run.",
            file=sys.stderr,
        )
        return 1

    drift_warnings = surface_drift_warnings(toml_data.get("tool", []))
    if drift_warnings:
        print(
            "surface drift (warn-only — enforcement lands with "
            "PLAN_serena-alignment-p1 Phase 2, see #346):",
            file=sys.stderr,
        )
        for line in drift_warnings:
            print(f"  - {line}", file=sys.stderr)

    rendered = render()

    if args.write:
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        BUILD_GEN.write_text(rendered)
        # rustfmt the generated file so subsequent `cargo fmt --check` is
        # a no-op. Without this the script emits `Tool::new(\n    ...\n).chain,`
        # but rustfmt rewrites the trailing chain onto a new line, and
        # the next `--check` run sees drift.
        subprocess.run(
            ["cargo", "fmt", "--", str(BUILD_GEN)],
            check=True,
            cwd=REPO_ROOT,
        )
        print(f"wrote {BUILD_GEN.relative_to(REPO_ROOT)}")
        return 0

    if not BUILD_GEN.exists():
        print(
            f"missing {BUILD_GEN.relative_to(REPO_ROOT)} — run "
            "`python3 scripts/regen-tool-defs.py --write`",
            file=sys.stderr,
        )
        return 1
    # Compare against rustfmt-normalised expected content so drift
    # detection is stable across rustfmt versions.
    fmt = subprocess.run(
        ["rustfmt", "--emit=stdout", "--quiet"],
        input=rendered,
        text=True,
        capture_output=True,
        check=True,
    )
    expected = fmt.stdout
    actual = BUILD_GEN.read_text()
    if actual != expected:
        print(
            f"drift in {BUILD_GEN.relative_to(REPO_ROOT)} — run "
            "`python3 scripts/regen-tool-defs.py --write`",
            file=sys.stderr,
        )
        return 1
    print(f"ok: {BUILD_GEN.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
