#!/usr/bin/env python3
"""Regenerate tool definition Rust modules from `tools.toml`.

This is the codegen counterpart of ADR-0013. The single source of truth
is `crates/codelens-mcp/tools.toml`; the generated output lives next to
the hand-edited tool registry under
`crates/codelens-mcp/src/tool_defs/generated/`.

Usage:
    python3 scripts/regen-tool-defs.py --write   # rewrite generated files
    python3 scripts/regen-tool-defs.py --check   # exit 1 on drift, print hint

The migration is per-category (ADR-0013 §Decision §4). PR-A scaffolds
the file_io category only; subsequent PRs extend `tools.toml` and the
emit table below.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS_TOML = REPO_ROOT / "crates" / "codelens-mcp" / "tools.toml"
OUT_DIR = REPO_ROOT / "crates" / "codelens-mcp" / "src" / "tool_defs" / "generated"
BUILD_GEN = OUT_DIR / "build_generated.rs"

SUPPORTED_SCHEMA = "v1"

# Map TOML `annotations` strings to the Rust local-variable name in
# `tool_defs/build.rs::build_tools`. Extend this table as new categories
# migrate; the category emit function only takes the bindings its tools
# actually reference (see `bindings_for_category` below).
ANNOTATION_BINDINGS: dict[str, str] = {
    "ro_p": "ro_p",
    "ro_a": "ro_a",
    "ro_w": "ro_w",
    "ro": "ro",
    "mut_p": "mut_p",
    "mut_w": "mut_w",
    "mutating": "mutating",
    "destructive": "destructive",
    "dest_a": "dest_a",
    # `mutating` flavour with audit_category="coordination" but no
    # approval_required — used by the multi-agent advisory tools
    # (register_agent_work, claim_files, release_files).
    "mut_coord": "mut_coord",
}

HEADER = """//! AUTO-GENERATED by `scripts/regen-tool-defs.py`. DO NOT EDIT.
//!
//! Source: `crates/codelens-mcp/tools.toml`
//! Run `python3 scripts/regen-tool-defs.py --write` to refresh.
//!
//! See `docs/adr/ADR-0013-tool-defs-codegen.md` for the migration plan.

#![allow(clippy::too_many_lines)]

use crate::protocol::{Tool, ToolAnnotations};
use crate::tool_defs::output_schemas::*;
use serde_json::json;
"""


def bindings_for_category(tools: list[dict[str, Any]]) -> list[str]:
    """Sorted unique annotation bindings used by a category's tools."""
    used = {tool.get("annotations", "ro_p") for tool in tools}
    for ann in used:
        if ann not in ANNOTATION_BINDINGS:
            raise SystemExit(
                f"annotations='{ann}' is not wired into regen-tool-defs.py. "
                "Extend ANNOTATION_BINDINGS first."
            )
    return sorted(used)


def render_tool(tool: dict[str, Any]) -> list[str]:
    name = tool["name"]
    desc = tool["description"]
    schema = tool["input_schema"]
    ann_key = tool.get("annotations", "ro_p")
    ann_var = ANNOTATION_BINDINGS[ann_key]
    schema_json = json.dumps(
        schema, separators=(",", ":"), sort_keys=False, ensure_ascii=False
    )

    builder_chain = []
    if "output_schema" in tool:
        builder_chain.append(f".with_output_schema({tool['output_schema']}())")
    builder_chain.append(f".with_annotations({ann_var}.clone())")
    if "max_response_tokens" in tool:
        builder_chain.append(
            f".with_max_response_tokens({int(tool['max_response_tokens'])})"
        )
    chain = "".join(builder_chain)

    return [
        "        Tool::new(",
        f"            {json.dumps(name, ensure_ascii=False)},",
        f"            {json.dumps(desc, ensure_ascii=False)},",
        f"            json!({schema_json}),",
        f"        ){chain},",
    ]


def render_category(category: str, tools: list[dict[str, Any]]) -> str:
    bindings = bindings_for_category(tools)
    args = ", ".join(f"{ANNOTATION_BINDINGS[b]}: &ToolAnnotations" for b in bindings)
    # `pub` here is intentionally permissive at the function level; the
    # narrow `pub(super) use` re-export in `tool_defs/generated/mod.rs`
    # is what actually constrains visibility to `tool_defs`. See
    # ADR-0013 for the visibility model.
    lines = [
        f"pub fn {category}_tools({args}) -> Vec<Tool> {{",
        "    vec![",
    ]
    for t in tools:
        lines.extend(render_tool(t))
    lines.append("    ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render() -> str:
    with TOOLS_TOML.open("rb") as f:
        data = tomllib.load(f)
    if data.get("schema_version") != SUPPORTED_SCHEMA:
        raise SystemExit(
            f"tools.toml schema_version='{data.get('schema_version')}' is not "
            f"supported by this script ({SUPPORTED_SCHEMA})"
        )
    by_category: dict[str, list[dict[str, Any]]] = {}
    for tool in data.get("tool", []):
        by_category.setdefault(tool["category"], []).append(tool)

    parts: list[str] = [HEADER]
    for category in sorted(by_category):
        parts.append("")
        parts.append(render_category(category, by_category[category]))
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="rewrite generated files")
    mode.add_argument("--check", action="store_true", help="exit 1 on drift")
    args = parser.parse_args()

    rendered = render()

    if args.write:
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        BUILD_GEN.write_text(rendered)
        # rustfmt the generated file so subsequent `cargo fmt --check` is
        # a no-op. Without this the script emits `Tool::new(\n    ...\n).chain,`
        # but rustfmt rewrites the trailing chain onto a new line, and
        # the next `--check` run sees drift.
        subprocess.run(
            ["cargo", "fmt", "--", str(BUILD_GEN)],
            check=True,
            cwd=REPO_ROOT,
        )
        print(f"wrote {BUILD_GEN.relative_to(REPO_ROOT)}")
        return 0

    if not BUILD_GEN.exists():
        print(
            f"missing {BUILD_GEN.relative_to(REPO_ROOT)} — run "
            "`python3 scripts/regen-tool-defs.py --write`",
            file=sys.stderr,
        )
        return 1
    # Compare against rustfmt-normalised expected content so drift
    # detection is stable across rustfmt versions.
    fmt = subprocess.run(
        ["rustfmt", "--emit=stdout", "--quiet"],
        input=rendered,
        text=True,
        capture_output=True,
        check=True,
    )
    expected = fmt.stdout
    actual = BUILD_GEN.read_text()
    if actual != expected:
        print(
            f"drift in {BUILD_GEN.relative_to(REPO_ROOT)} — run "
            "`python3 scripts/regen-tool-defs.py --write`",
            file=sys.stderr,
        )
        return 1
    print(f"ok: {BUILD_GEN.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
