#!/usr/bin/env python3
"""Regenerate tool definition Rust modules from `tools.toml`.

This is the codegen counterpart of ADR-0013. The single source of truth
is `crates/codelens-mcp/tools.toml`; the generated output lives next to
the hand-edited tool registry under
`crates/codelens-mcp/src/tool_defs/generated/`.

Usage:
    python3 scripts/regen-tool-defs.py --write   # rewrite generated files
    python3 scripts/regen-tool-defs.py --check   # exit 1 on drift, print hint

The migration is per-category (ADR-0013 §Decision §4). PR-A scaffolds
the file_io category only; subsequent PRs extend `tools.toml` and the
emit table below.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS_TOML = REPO_ROOT / "crates" / "codelens-mcp" / "tools.toml"
OUT_DIR = REPO_ROOT / "crates" / "codelens-mcp" / "src" / "tool_defs" / "generated"
BUILD_GEN = OUT_DIR / "build_generated.rs"
METADATA_GEN = OUT_DIR / "metadata_generated.rs"
PRESETS_RS = REPO_ROOT / "crates" / "codelens-mcp" / "src" / "tool_defs" / "presets.rs"

SUPPORTED_SCHEMA = "v1"
VALID_PHASES = {"plan", "build", "review", "eval"}
VALID_NAMESPACES = {"filesystem", "symbols", "graph", "reports", "memory", "lsp", "session"}

# Maps the `preset_tags` token used in tools.toml to the Rust constant in
# `tool_defs/presets.rs` that should mirror its inversion. Drift between
# the two surfaces is a CI failure (see `validate_preset_tags`). #200
# stage 2 only validates equivalence; stage 3 will switch the Rust side
# to a codegen path so tools.toml becomes the single source.
PRESET_TAG_TO_CONST: dict[str, str] = {
    "minimal": "MINIMAL_TOOLS",
    "balanced-excluded": "BALANCED_EXCLUDES",
    "planner-readonly": "PLANNER_READONLY_TOOLS",
    "builder-minimal": "BUILDER_MINIMAL_TOOLS",
    "reviewer-graph": "REVIEWER_GRAPH_TOOLS",
}

# Map TOML `annotations` strings to the Rust local-variable name in
# `tool_defs/build.rs::build_tools`. Extend this table as new categories
# migrate; the category emit function only takes the bindings its tools
# actually reference (see `bindings_for_category` below).
ANNOTATION_BINDINGS: dict[str, str] = {
    "ro_p": "ro_p",
    "ro_a": "ro_a",
    "ro_w": "ro_w",
    "ro": "ro",
    "mut_p": "mut_p",
    "mut_w": "mut_w",
    "mutating": "mutating",
    "destructive": "destructive",
    "dest_a": "dest_a",
    # `mutating` flavour with audit_category="coordination" but no
    # approval_required — used by the multi-agent advisory tools
    # (register_agent_work, claim_files, release_files).
    "mut_coord": "mut_coord",
}

HEADER = """//! AUTO-GENERATED by `scripts/regen-tool-defs.py`. DO NOT EDIT.
//!
//! Source: `crates/codelens-mcp/tools.toml`
//! Run `python3 scripts/regen-tool-defs.py --write` to refresh.
//!
//! See `docs/adr/ADR-0013-tool-defs-codegen.md` for the migration plan.

#![allow(clippy::too_many_lines)]

use crate::protocol::{Tool, ToolAnnotations};
use crate::tool_defs::output_schemas::*;
use serde_json::json;
"""

METADATA_HEADER = """//! AUTO-GENERATED by `scripts/regen-tool-defs.py`. DO NOT EDIT.
//!
//! Source: `crates/codelens-mcp/tools.toml`
//! Run `python3 scripts/regen-tool-defs.py --write` to refresh.

"""


def bindings_for_category(tools: list[dict[str, Any]]) -> list[str]:
    """Sorted unique annotation bindings used by a category's tools."""
    used = {tool.get("annotations", "ro_p") for tool in tools}
    for ann in used:
        if ann not in ANNOTATION_BINDINGS:
            raise SystemExit(
                f"annotations='{ann}' is not wired into regen-tool-defs.py. "
                "Extend ANNOTATION_BINDINGS first."
            )
    return sorted(used)


def render_tool(tool: dict[str, Any]) -> list[str]:
    name = tool["name"]
    desc = tool["description"]
    schema = tool["input_schema"]
    ann_key = tool.get("annotations", "ro_p")
    ann_var = ANNOTATION_BINDINGS[ann_key]
    schema_json = json.dumps(
        schema, separators=(",", ":"), sort_keys=False, ensure_ascii=False
    )

    builder_chain = []
    if "output_schema" in tool:
        builder_chain.append(f".with_output_schema({tool['output_schema']}())")
    builder_chain.append(f".with_annotations({ann_var}.clone())")
    if "max_response_tokens" in tool:
        builder_chain.append(
            f".with_max_response_tokens({int(tool['max_response_tokens'])})"
        )
    chain = "".join(builder_chain)

    return [
        "        Tool::new(",
        f"            {json.dumps(name, ensure_ascii=False)},",
        f"            {json.dumps(desc, ensure_ascii=False)},",
        f"            json!({schema_json}),",
        f"        ){chain},",
    ]


def category_feature_gate(tools: list[dict[str, Any]]) -> str | None:
    """Return the shared `feature_gate` if every tool agrees, else None.

    The codegen only supports an all-or-nothing feature gate per
    category — the calling convention in `build.rs` extends one Vec
    per category, so a mixed category would need per-Tool cfg
    attributes inside the vec, which the script does not emit. If a
    future PR needs a mixed category, update this function and the
    Tool::new emit path together.
    """
    gates = {tool.get("feature_gate") for tool in tools}
    if len(gates) > 1:
        raise SystemExit(
            f"tools in the same category disagree on feature_gate: {gates}. "
            "Split into separate categories."
        )
    return next(iter(gates))


def render_category(category: str, tools: list[dict[str, Any]]) -> str:
    bindings = bindings_for_category(tools)
    args = ", ".join(f"{ANNOTATION_BINDINGS[b]}: &ToolAnnotations" for b in bindings)
    # `pub` here is intentionally permissive at the function level; the
    # narrow `pub(super) use` re-export in `tool_defs/generated/mod.rs`
    # is what actually constrains visibility to `tool_defs`. See
    # ADR-0013 for the visibility model.
    lines: list[str] = []
    gate = category_feature_gate(tools)
    if gate is not None:
        lines.append(f'#[cfg(feature = "{gate}")]')
    lines.append(f"pub fn {category}_tools({args}) -> Vec<Tool> {{")
    lines.append("    vec![")
    for t in tools:
        lines.extend(render_tool(t))
    lines.append("    ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _strip_line_comments(src: str) -> str:
    """Drop `// ...` tails line-wise so quoted names inside comments
    (doc examples, commented-out registrations) never count as matches."""
    cleaned_lines: list[str] = []
    for line in src.split("\n"):
        idx = line.find("//")
        cleaned_lines.append(line if idx < 0 else line[:idx])
    return "\n".join(cleaned_lines)


def extract_preset_const(name: str, src: str) -> set[str]:
    """Return the &str literals inside `pub(crate) const <name>: &[&str] = &[ ... ];`.

    Strips `// ...` line comments from the body before extracting string
    literals — the constants contain prose rationale that would
    otherwise contribute false-positive matches.
    """
    pat = re.compile(
        rf"pub\(crate\) const {re.escape(name)}: &\[&str\] = &\[(.*?)\];",
        re.DOTALL,
    )
    m = pat.search(src)
    if not m:
        raise SystemExit(f"could not locate const {name} in presets.rs")
    cleaned = _strip_line_comments(m.group(1))
    return set(re.findall(r'"([^"]+)"', cleaned))


# ── Surface drift report + description lint ────────────────────────────
# PLAN_serena-alignment-p1 Phase 1 (#346). Warn-only until Phase 2
# resolves the known ghosts and flips on enforcement.

DISPATCH_SOURCES: tuple[Path, ...] = (
    REPO_ROOT / "crates" / "codelens-mcp" / "src" / "tools" / "mod.rs",
    REPO_ROOT / "crates" / "codelens-mcp" / "src" / "dispatch" / "table.rs",
)

# Dispatch-only names sanctioned while ADR-0009/D3 decides the symbolic edit
# surface (spec 2026-06-10 §D3). The combined allowlist remains visible as
# `allowlisted_dispatch_only`; the split buckets keep the re-list candidates
# distinct from substrate-preservation candidates.
PENDING_D3_SYMBOLIC_EDIT_CORE: frozenset[str] = frozenset(
    {
        "replace_symbol_body",
        "insert_before_symbol",
        "insert_after_symbol",
        "rename_symbol",
    }
)

# These dispatch arms are the only callers keeping the semantic_edit substrate
# alive; ADR-0009/D3 decides re-list vs delete. Removing them now would
# dead-code the substrate that decision needs intact.
PENDING_D3_REFACTOR_SUBSTRATE: frozenset[str] = frozenset(
    {
        "refactor_extract_function",
        "refactor_inline_function",
        "refactor_move_to_file",
        "refactor_change_signature",
        "propagate_deletions",
    }
)

DISPATCH_ONLY_ALLOWLIST: frozenset[str] = (
    PENDING_D3_SYMBOLIC_EDIT_CORE | PENDING_D3_REFACTOR_SUBSTRATE
)

# (tool, referenced_tool) description cross-references that are
# intentionally allowed. Keep empty unless a pairing is genuinely
# load-bearing; chaining belongs in suggested_next_tools (spec D7).
#
# The verb facades (search / graph / review — Phase-1/2 consolidation)
# are deliberately named with common English words. The D7 word-boundary
# check therefore false-positives whenever a PRE-EXISTING description uses
# those words organically ("partial-identifier search", "call graph",
# "review changed files") — none of these are chaining name-drops. Each
# pairing below is such an organic collision, reviewed and exempted; the
# verbs' own descriptions avoid naming their target tools (D7-clean).
DESCRIPTION_XREF_ALLOWLIST: frozenset[tuple[str, str]] = frozenset(
    {
        ("get_ranked_context", "search"),
        ("search_symbols_fuzzy", "search"),
        ("search_workspace_symbols", "search"),
        ("semantic_search", "search"),
        ("index_embeddings", "search"),
        ("cleanup_duplicate_logic", "search"),
        ("get_callers", "graph"),
        ("prepare_harness_session", "graph"),
        ("get_changed_files", "review"),
        ("review_changes", "review"),
    }
)


def parse_dispatch_names(src: str) -> set[str]:
    """Extract tool names from dispatch-registration source text.

    Handles both registration styles in this repo:
      1. `tool_registry!` match arms — `"name" => module::handler,`
      2. handler-map inserts — `m.insert("name", std::sync::Arc::new(handler))`,
         including the rustfmt multi-line form. The `Arc::new` requirement
         keeps serde_json payload inserts inside handler bodies
         (`payload.insert("provenance", json!(..))`) from counting.
    """
    stripped = _strip_line_comments(src)
    names = set(re.findall(r'"([A-Za-z0-9_]+)"\s*=>', stripped))
    names |= set(
        re.findall(
            r'\.insert\(\s*"([A-Za-z0-9_]+)"\s*,\s*(?:std::sync::)?Arc::new',
            stripped,
        )
    )
    return names


def collect_dispatch_names() -> set[str]:
    """Union of dispatch names across all known registration sites."""
    names: set[str] = set()
    for path in DISPATCH_SOURCES:
        names |= parse_dispatch_names(path.read_text())
    return names


def three_way_report(
    dispatch: set[str],
    schema: set[str],
    preset_members: set[str],
    dispatch_only_allowlist: frozenset[str] | set[str] = frozenset(),
) -> dict[str, list[str]]:
    """Classify surface drift between the three registries.

    - dispatch_only: callable but schemaless — invisible to tools/list
    - allowlisted_dispatch_only: sanctioned pending-D3 exceptions
    - pending_d3_symbolic_edit_core: re-list candidates within the allowlist
    - pending_d3_refactor_substrate: substrate-preservation candidates
    - schema_only: listed but not dispatchable — dead schema
    - preset_dead: preset members without a tools.toml definition —
      strings the surface filter can never match
    """
    dispatch_only = dispatch - schema
    allow = set(dispatch_only_allowlist)
    return {
        "dispatch_only": sorted(dispatch_only - allow),
        "allowlisted_dispatch_only": sorted(dispatch_only & allow),
        "pending_d3_symbolic_edit_core": sorted(
            dispatch_only & PENDING_D3_SYMBOLIC_EDIT_CORE
        ),
        "pending_d3_refactor_substrate": sorted(
            dispatch_only & PENDING_D3_REFACTOR_SUBSTRATE
        ),
        "schema_only": sorted(schema - dispatch),
        # Allowlisted (pending-D3) names may legitimately sit in preset
        # constants — callable-but-unlisted on their surfaces.
        "preset_dead": sorted(preset_members - schema - allow),
    }


def lint_description_crossrefs(
    tools: list[dict[str, Any]],
    allowlist: frozenset[tuple[str, str]] | set[tuple[str, str]] = DESCRIPTION_XREF_ALLOWLIST,
) -> list[str]:
    """Flag descriptions that reference other tools by name (spec D7).

    Tool-search surfaces retrieve descriptions independently; chaining
    guidance belongs in suggested_next_tools, not prose name-drops.
    Word-boundary match; self-references are fine.
    """
    names = {tool["name"] for tool in tools}
    offenses: list[str] = []
    for tool in tools:
        desc = tool.get("description", "") or ""
        for other in sorted(names - {tool["name"]}):
            if (tool["name"], other) in allowlist:
                continue
            if re.search(rf"\b{re.escape(other)}\b", desc):
                offenses.append(
                    f"{tool['name']}: description references tool `{other}` "
                    "(move chaining to suggested_next_tools — spec D7)"
                )
    return offenses


def extract_tombstones(src: str) -> set[str]:
    """Names in the `TOMBSTONED_TOOLS: &[(&str, &str)]` const (tools/mod.rs).

    Tombstoned names must never reappear in dispatch, tools.toml, or
    preset constants (Serena `_deleted_tools` pattern).
    """
    m = re.search(
        r"const TOMBSTONED_TOOLS: &\[\(&str, &str\)\] = &\[(.*?)\];",
        src,
        re.DOTALL,
    )
    if not m:
        return set()
    cleaned = _strip_line_comments(m.group(1))
    return set(re.findall(r'\(\s*"([A-Za-z0-9_]+)"\s*,', cleaned))


def enforce_failures(
    report: dict[str, list[str]],
    lint_offenses: list[str],
    tombstone_hits: list[str],
) -> list[str]:
    """Blocking lines for `--enforce-drift`. Allowlisted entries pass."""
    fails: list[str] = []
    for key in ("dispatch_only", "schema_only", "preset_dead"):
        if report[key]:
            fails.append(f"{key} ({len(report[key])}): {', '.join(report[key])}")
    fails.extend(lint_offenses)
    fails.extend(tombstone_hits)
    return fails


def collect_surface_state(
    tools: list[dict[str, Any]],
) -> tuple[dict[str, list[str]], list[str], list[str]]:
    """Live (report, lint_offenses, tombstone_hits) for the working tree."""
    schema_names = {tool["name"] for tool in tools}
    presets_src = PRESETS_RS.read_text()
    preset_members: set[str] = set()
    for const_name in PRESET_TAG_TO_CONST.values():
        preset_members |= extract_preset_const(const_name, presets_src)
    dispatch = collect_dispatch_names()
    report = three_way_report(
        dispatch,
        schema_names,
        preset_members,
        dispatch_only_allowlist=DISPATCH_ONLY_ALLOWLIST,
    )
    lint_offenses = lint_description_crossrefs(tools)
    tombstone_hits: list[str] = []
    tombstones = extract_tombstones(DISPATCH_SOURCES[0].read_text())
    for name in sorted(tombstones):
        if name in dispatch:
            tombstone_hits.append(f"tombstoned tool `{name}` re-introduced in dispatch")
        if name in schema_names:
            tombstone_hits.append(f"tombstoned tool `{name}` re-introduced in tools.toml")
        if name in preset_members:
            tombstone_hits.append(f"tombstoned tool `{name}` re-introduced in presets.rs")
    return report, lint_offenses, tombstone_hits



def validate_preset_tags(tools: list[dict[str, Any]]) -> list[str]:
    """Return human-readable mismatch lines between preset_tags and presets.rs.

    Inverts `[[tool]].preset_tags` into one set per preset tag. The Rust
    side holds the same data as five `pub(crate) const <NAME>: &[&str]`
    arrays in `tool_defs/presets.rs`. The two must agree **for tools
    that exist in tools.toml**. Members listed in presets.rs but absent
    from tools.toml ("orphans" — dead members `tools()` cannot surface)
    are reported by `surface_drift_warnings` as `preset_dead`.
    """
    src = PRESETS_RS.read_text()
    tools_in_toml = {tool["name"] for tool in tools}

    inverse: dict[str, set[str]] = {tag: set() for tag in PRESET_TAG_TO_CONST}
    for tool in tools:
        for tag in tool.get("preset_tags", []) or []:
            if tag in inverse:
                inverse[tag].add(tool["name"])

    mismatches: list[str] = []

    for tag, const_name in PRESET_TAG_TO_CONST.items():
        toml_set = inverse.get(tag, set())
        rs_set = extract_preset_const(const_name, src)
        rs_in_toml = rs_set & tools_in_toml
        only_toml = toml_set - rs_in_toml
        only_rs = rs_in_toml - toml_set
        if only_toml:
            mismatches.append(
                f"{const_name}: in tools.toml preset_tags but not in "
                f"presets.rs: {sorted(only_toml)}"
            )
        if only_rs:
            mismatches.append(
                f"{const_name}: in presets.rs but missing from "
                f"tools.toml preset_tags: {sorted(only_rs)}"
            )

    unknown_tags: set[str] = set()
    for tool in tools:
        for tag in tool.get("preset_tags", []) or []:
            if tag not in PRESET_TAG_TO_CONST:
                unknown_tags.add(tag)
    if unknown_tags:
        mismatches.append(
            f"unknown preset_tags values (not in PRESET_TAG_TO_CONST): "
            f"{sorted(unknown_tags)}"
        )
    return mismatches


def render() -> str:
    with TOOLS_TOML.open("rb") as f:
        data = tomllib.load(f)
    if data.get("schema_version") != SUPPORTED_SCHEMA:
        raise SystemExit(
            f"tools.toml schema_version='{data.get('schema_version')}' is not "
            f"supported by this script ({SUPPORTED_SCHEMA})"
        )
    by_category: dict[str, list[dict[str, Any]]] = {}
    for tool in data.get("tool", []):
        by_category.setdefault(tool["category"], []).append(tool)

    parts: list[str] = [HEADER]
    for category in sorted(by_category):
        parts.append("")
        parts.append(render_category(category, by_category[category]))
    return "\n".join(parts).rstrip() + "\n"


def render_option_match(
    fn_name: str,
    values: dict[str, str],
) -> str:
    lines = [
        f"pub(in crate::tool_defs) fn {fn_name}(name: &str) -> Option<&'static str> {{",
        "    match name {",
    ]
    for name in sorted(values):
        lines.append(f'        "{name}" => Some("{values[name]}"),')
    lines.extend(["        _ => None,", "    }", "}", ""])
    return "\n".join(lines)


def collect_default_listed_tools(tools: list[dict[str, Any]]) -> list[str]:
    """Return `default_visible_rank` tools sorted by rank.

    The default MCP tools/list payload is the expensive first prompt
    surface, so it must be explicit, ordered, and bounded from the same
    declarative source as the rest of the tool metadata.
    """
    ranked: list[tuple[int, str]] = []
    seen_ranks: dict[int, str] = {}
    for tool in tools:
        rank = tool.get("default_visible_rank")
        if rank is None:
            continue
        name = tool["name"]
        if not isinstance(rank, int) or isinstance(rank, bool) or rank <= 0:
            raise SystemExit(
                f"{name}: default_visible_rank must be a positive integer"
            )
        if rank in seen_ranks:
            raise SystemExit(
                f"{name}: default_visible_rank={rank} duplicates "
                f"{seen_ranks[rank]}"
            )
        seen_ranks[rank] = name
        ranked.append((rank, name))

    if not 5 <= len(ranked) <= 9:
        raise SystemExit(
            "default_visible_rank must mark 5-9 tools; "
            f"found {len(ranked)}"
        )
    return [name for _, name in sorted(ranked)]


def render_default_listed_tool_names(names: list[str]) -> str:
    lines = [
        "pub(in crate::tool_defs) fn default_listed_tool_names() -> &'static [&'static str] {",
        "    &[",
    ]
    for name in names:
        lines.append(f'        "{name}",')
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def render_bool_match(fn_name: str, names: list[str]) -> str:
    lines = [
        f"pub(in crate::tool_defs) fn {fn_name}(name: &str) -> bool {{",
        "    matches!(",
        "        name,",
    ]
    for idx, name in enumerate(names):
        prefix = "        " if idx == 0 else "            | "
        lines.append(f'{prefix}"{name}"')
    lines.extend(["    )", "}", ""])
    return "\n".join(lines)


def render_metadata() -> str:
    with TOOLS_TOML.open("rb") as f:
        data = tomllib.load(f)
    if data.get("schema_version") != SUPPORTED_SCHEMA:
        raise SystemExit(
            f"tools.toml schema_version='{data.get('schema_version')}' is not "
            f"supported by this script ({SUPPORTED_SCHEMA})"
        )

    feature_gates: dict[str, str] = {}
    phases: dict[str, str] = {}
    namespaces: dict[str, str] = {}
    annotations: dict[str, str] = {}
    default_listed = collect_default_listed_tools(data.get("tool", []))
    content_mutation_tools = data.get("content_mutation_tools", [])
    symbol_generation_consistent_tools = data.get(
        "symbol_generation_consistent_tools", []
    )
    experimental_tools: dict[str, str] = {}
    for feature, names in data.get("experimental_features", {}).items():
        for name in names:
            experimental_tools[name] = feature

    for tool in data.get("tool", []):
        name = tool["name"]
        if gate := tool.get("feature_gate"):
            feature_gates[name] = gate
        if phase := tool.get("phase"):
            if phase not in VALID_PHASES:
                raise SystemExit(
                    f"{name}: phase='{phase}' is not supported; "
                    f"expected one of {sorted(VALID_PHASES)}"
                )
            phases[name] = phase
        namespace = tool.get("namespace")
        if not namespace:
            raise SystemExit(f"{name}: missing required namespace in tools.toml")
        if namespace not in VALID_NAMESPACES:
            raise SystemExit(
                f"{name}: namespace='{namespace}' is not supported; "
                f"expected one of {sorted(VALID_NAMESPACES)}"
            )
        namespaces[name] = namespace
        annotations[name] = tool.get("annotations", "ro_p")

    parts = [METADATA_HEADER.rstrip(), ""]
    parts.append(render_default_listed_tool_names(default_listed))
    parts.append(render_bool_match("tool_default_listed", default_listed))
    parts.append(render_bool_match("tool_is_content_mutation", content_mutation_tools))
    parts.append(
        render_bool_match(
            "tool_symbol_generation_consistent", symbol_generation_consistent_tools
        )
    )
    parts.append(render_option_match("tool_experimental_feature", experimental_tools))
    parts.append(render_option_match("tool_feature_gate", feature_gates))
    parts.append(render_option_match("tool_phase", phases))
    parts.append(render_option_match("tool_namespace", namespaces))
    parts.append(render_option_match("tool_annotation_key", annotations))
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="rewrite generated files")
    mode.add_argument("--check", action="store_true", help="exit 1 on drift")
    parser.add_argument(
        "--enforce-drift",
        action="store_true",
        help="exit 1 on unexplained surface drift / lint / tombstone hits (#346)",
    )
    args = parser.parse_args()

    with TOOLS_TOML.open("rb") as f:
        toml_data = tomllib.load(f)
    preset_mismatches = validate_preset_tags(toml_data.get("tool", []))
    if preset_mismatches:
        print(
            "preset_tags drift between tools.toml and "
            "crates/codelens-mcp/src/tool_defs/presets.rs:",
            file=sys.stderr,
        )
        for line in preset_mismatches:
            print(f"  - {line}", file=sys.stderr)
        print(
            "edit tools.toml preset_tags or presets.rs constants so they "
            "agree, then re-run.",
            file=sys.stderr,
        )
        return 1

    report, lint_offenses, tombstone_hits = collect_surface_state(
        toml_data.get("tool", [])
    )
    blocking = enforce_failures(report, lint_offenses, tombstone_hits)
    info_lines = list(blocking)
    if report["allowlisted_dispatch_only"]:
        info_lines.append(
            "allowlisted_dispatch_only (pending-D3): "
            + ", ".join(report["allowlisted_dispatch_only"])
        )
        if report["pending_d3_symbolic_edit_core"]:
            info_lines.append(
                "pending_d3_symbolic_edit_core: "
                + ", ".join(report["pending_d3_symbolic_edit_core"])
            )
        if report["pending_d3_refactor_substrate"]:
            info_lines.append(
                "pending_d3_refactor_substrate: "
                + ", ".join(report["pending_d3_refactor_substrate"])
            )
    if info_lines:
        label = "blocking" if (args.enforce_drift and blocking) else "info"
        print(f"surface drift ({label}, #346):", file=sys.stderr)
        for line in info_lines:
            print(f"  - {line}", file=sys.stderr)
    if args.enforce_drift and blocking:
        print(
            "--enforce-drift: unexplained surface drift — register the tool "
            "in tools.toml, tombstone it, or extend the pending-D3 allowlist.",
            file=sys.stderr,
        )
        return 1

    rendered = render()

    if args.write:
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        BUILD_GEN.write_text(rendered)
        METADATA_GEN.write_text(render_metadata())
        # rustfmt the generated file so subsequent `cargo fmt --check` is
        # a no-op. Without this the script emits `Tool::new(\n    ...\n).chain,`
        # but rustfmt rewrites the trailing chain onto a new line, and
        # the next `--check` run sees drift.
        subprocess.run(
            ["cargo", "fmt", "--", str(BUILD_GEN), str(METADATA_GEN)],
            check=True,
            cwd=REPO_ROOT,
        )
        print(f"wrote {BUILD_GEN.relative_to(REPO_ROOT)}")
        print(f"wrote {METADATA_GEN.relative_to(REPO_ROOT)}")
        return 0

    if not BUILD_GEN.exists():
        print(
            f"missing {BUILD_GEN.relative_to(REPO_ROOT)} — run "
            "`python3 scripts/regen-tool-defs.py --write`",
            file=sys.stderr,
        )
        return 1
    # Compare against rustfmt-normalised expected content so drift
    # detection is stable across rustfmt versions.
    fmt = subprocess.run(
        ["rustfmt", "--emit=stdout", "--quiet"],
        input=rendered,
        text=True,
        capture_output=True,
        check=True,
    )
    expected = fmt.stdout
    actual = BUILD_GEN.read_text()
    if actual != expected:
        print(
            f"drift in {BUILD_GEN.relative_to(REPO_ROOT)} — run "
            "`python3 scripts/regen-tool-defs.py --write`",
            file=sys.stderr,
        )
        return 1
    if not METADATA_GEN.exists():
        print(
            f"missing {METADATA_GEN.relative_to(REPO_ROOT)} — run "
            "`python3 scripts/regen-tool-defs.py --write`",
            file=sys.stderr,
        )
        return 1
    metadata_fmt = subprocess.run(
        ["rustfmt", "--emit=stdout", "--quiet"],
        input=render_metadata(),
        text=True,
        capture_output=True,
        check=True,
    )
    metadata_expected = metadata_fmt.stdout
    metadata_actual = METADATA_GEN.read_text()
    if metadata_actual != metadata_expected:
        print(
            f"drift in {METADATA_GEN.relative_to(REPO_ROOT)} — run "
            "`python3 scripts/regen-tool-defs.py --write`",
            file=sys.stderr,
        )
        return 1
    print(f"ok: {BUILD_GEN.relative_to(REPO_ROOT)}")
    print(f"ok: {METADATA_GEN.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
