//! Phase P6-a — routing policy as code.
//!
//! The goal of Pillar 6 in `docs/plans/PLAN_extreme-efficiency.md` is
//! that the "CodeLens vs native" routing decision lives in code, not
//! in drift-prone markdown. This module declares the policy as a
//! typed table and emits a deterministic markdown rendering; the
//! checked-in snapshot at `docs/routing-policy.md` is generated from
//! this source of truth, and the integration test
//! `routing_policy_table_compiles_to_markdown_identical_to_checked_in_file`
//! guards round-trip equivalence.
//!
//! Scope for this slice: the declarative table + the generator +
//! the snapshot. The full evaluation harness that compares CodeLens
//! vs native vs hybrid on 10 synthetic tasks is Phase P6-b.

/// A routing rule: which task shape maps to which execution lane,
/// plus a short rationale sentence for the generated markdown.
#[derive(Clone, Copy, Debug)]
pub(crate) struct RoutingRule {
    pub task_shape: &'static str,
    pub lane: RoutingLane,
    pub rationale: &'static str,
}

/// The lane the harness should pick for a given task shape. Names
/// mirror the executor labels the CodeLens CLI already emits so the
/// generator can surface them without translation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum RoutingLane {
    Native,
    CodeLensAfterBootstrap,
    AsyncAnalysis,
}

impl RoutingLane {
    pub(crate) fn as_label(&self) -> &'static str {
        match self {
            RoutingLane::Native => "native",
            RoutingLane::CodeLensAfterBootstrap => "codelens_after_bootstrap",
            RoutingLane::AsyncAnalysis => "async_analysis",
        }
    }
}

/// The declarative routing table. Ordered deterministically so the
/// generated markdown is stable byte-for-byte across runs.
pub(crate) const ROUTING_RULES: &[RoutingRule] = &[
    RoutingRule {
        task_shape: "simple local lookup / single-file edit (<30 LOC)",
        lane: RoutingLane::Native,
        rationale: "Native Read/Grep is faster and bypasses CodeLens warm-up cost.",
    },
    RoutingRule {
        task_shape: "multi-file review or impact analysis",
        lane: RoutingLane::CodeLensAfterBootstrap,
        rationale: "Switch to CodeLens workflow tools after the first concrete local step for bounded blast-radius reports.",
    },
    RoutingRule {
        task_shape: "refactor preflight (rename / extract / move)",
        lane: RoutingLane::CodeLensAfterBootstrap,
        rationale: "Use verify_change_readiness + safe_rename_report before mutation tools.",
    },
    RoutingRule {
        task_shape: "onboarding / planning an unfamiliar repo",
        lane: RoutingLane::CodeLensAfterBootstrap,
        rationale: "onboard_project + get_ranked_context give better context-per-token than ad-hoc grep.",
    },
    RoutingRule {
        task_shape: "long-running analysis (dead_code, module_boundary)",
        lane: RoutingLane::AsyncAnalysis,
        rationale: "Use start_analysis_job + poll, not synchronous workflow tools; avoids blocking the session.",
    },
];

/// Render the routing table as markdown. The format is intentionally
/// minimal so the round-trip snapshot test is easy to read and
/// mechanical to regenerate.
pub(crate) fn render_routing_policy_markdown() -> String {
    let mut out = String::new();
    out.push_str("<!-- Generated by codelens-mcp::routing_policy::render_routing_policy_markdown. DO NOT EDIT BY HAND. -->\n");
    out.push_str("# CodeLens Routing Policy\n\n");
    out.push_str(
        "Authoritative routing table, kept in sync with `crates/codelens-mcp/src/routing_policy.rs`. \
         Regenerate via `cargo test -p codelens-mcp routing_policy` when the Rust table changes.\n\n",
    );
    out.push_str("| Task shape | Lane | Rationale |\n");
    out.push_str("| --- | --- | --- |\n");
    for rule in ROUTING_RULES {
        out.push_str(&format!(
            "| {} | `{}` | {} |\n",
            rule.task_shape,
            rule.lane.as_label(),
            rule.rationale,
        ));
    }
    out
}

/// Phase P6-b slice 1: a single evaluation task referenced by the
/// eval harness. Each scenario declares the expected routing lane
/// so Python/Rust runners can cross-check classification without
/// duplicating rules.
#[derive(Clone, Copy, Debug)]
pub(crate) struct EvalScenario {
    /// Stable identifier used by downstream metric files.
    pub id: &'static str,
    /// Human-readable one-line summary of the task.
    pub task: &'static str,
    /// Which lane this scenario is expected to route through when
    /// classified by the routing policy.
    pub expected_lane: RoutingLane,
}

/// Declarative 10-scenario battery the eval harness will run against
/// three arms (native, codelens, hybrid) per P6. Deterministic
/// order keeps the generated JSON stable across runs.
pub(crate) const EVAL_SCENARIOS: &[EvalScenario] = &[
    EvalScenario {
        id: "lookup_single_symbol",
        task: "Find the definition of `render_routing_policy_markdown`.",
        expected_lane: RoutingLane::Native,
    },
    EvalScenario {
        id: "edit_single_line",
        task: "Change a constant value in one file under 30 LOC.",
        expected_lane: RoutingLane::Native,
    },
    EvalScenario {
        id: "impact_report_multi_file",
        task: "Summarize the blast radius of modifying `tool_defs/output_schemas.rs`.",
        expected_lane: RoutingLane::CodeLensAfterBootstrap,
    },
    EvalScenario {
        id: "rename_across_workspace",
        task: "Rename `shared_analysis_pool_snapshot` across the workspace.",
        expected_lane: RoutingLane::CodeLensAfterBootstrap,
    },
    EvalScenario {
        id: "onboard_unfamiliar_repo",
        task: "Produce a first-look overview of an unfamiliar codebase.",
        expected_lane: RoutingLane::CodeLensAfterBootstrap,
    },
    EvalScenario {
        id: "extract_function",
        task: "Refactor a 40-line block into a new helper function.",
        expected_lane: RoutingLane::CodeLensAfterBootstrap,
    },
    EvalScenario {
        id: "audit_module_boundary",
        task: "Flag modules that leak internals across package boundaries.",
        expected_lane: RoutingLane::AsyncAnalysis,
    },
    EvalScenario {
        id: "dead_code_report_full_repo",
        task: "Enumerate dead code across the whole repo.",
        expected_lane: RoutingLane::AsyncAnalysis,
    },
    EvalScenario {
        id: "trace_call_path",
        task: "Trace the call path from `main` to `store_analysis`.",
        expected_lane: RoutingLane::CodeLensAfterBootstrap,
    },
    EvalScenario {
        id: "fix_single_bug",
        task: "Fix an off-by-one error reported by a failing unit test.",
        expected_lane: RoutingLane::Native,
    },
];

/// Serialize the scenario battery as JSON. Ordered list of objects
/// so downstream Python runners can zip with measured metrics.
pub(crate) fn render_eval_scenarios_json() -> String {
    let entries: Vec<_> = EVAL_SCENARIOS
        .iter()
        .map(|scenario| {
            serde_json::json!({
                "id": scenario.id,
                "task": scenario.task,
                "expected_lane": scenario.expected_lane.as_label(),
            })
        })
        .collect();
    let doc = serde_json::json!({
        "schema_version": 1,
        "generated_by": "codelens-mcp::routing_policy::render_eval_scenarios_json",
        "scenarios": entries,
    });
    // Pretty-printed so humans can diff the snapshot.
    let mut pretty = serde_json::to_string_pretty(&doc).unwrap_or_default();
    pretty.push('\n');
    pretty
}

/// Path of the checked-in scenarios JSON snapshot, relative to the
/// repo root.
pub(crate) const EVAL_SCENARIOS_SNAPSHOT_PATH: &str =
    "benchmarks/scenarios/extreme-efficiency.json";

pub(crate) fn eval_scenarios_snapshot_path() -> std::path::PathBuf {
    let manifest = env!("CARGO_MANIFEST_DIR");
    std::path::Path::new(manifest)
        .parent()
        .and_then(|p| p.parent())
        .expect("CARGO_MANIFEST_DIR must have a repo-root ancestor")
        .join(EVAL_SCENARIOS_SNAPSHOT_PATH)
}

/// Path of the checked-in markdown snapshot, relative to the repo root.
pub(crate) const ROUTING_POLICY_SNAPSHOT_PATH: &str = "docs/routing-policy.md";

/// Absolute path to the snapshot, resolved via `CARGO_MANIFEST_DIR`
/// so the round-trip test works from any cwd.
pub(crate) fn routing_policy_snapshot_path() -> std::path::PathBuf {
    let manifest = env!("CARGO_MANIFEST_DIR");
    std::path::Path::new(manifest)
        .parent()
        .and_then(|p| p.parent())
        .expect("CARGO_MANIFEST_DIR must have a repo-root ancestor")
        .join(ROUTING_POLICY_SNAPSHOT_PATH)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_lane_is_represented_in_the_table() {
        // Keeps the table from silently dropping a lane when a rule
        // is edited. If a new lane variant is added, at least one
        // rule must reference it so the markdown stays informative.
        let labels: std::collections::BTreeSet<_> = ROUTING_RULES
            .iter()
            .map(|rule| rule.lane.as_label())
            .collect();
        assert!(labels.contains("native"));
        assert!(labels.contains("codelens_after_bootstrap"));
        assert!(labels.contains("async_analysis"));
    }

    #[test]
    fn rendered_markdown_includes_header_and_row_per_rule() {
        let rendered = render_routing_policy_markdown();
        assert!(rendered.starts_with("<!-- Generated by"));
        assert!(rendered.contains("| Task shape | Lane | Rationale |"));
        for rule in ROUTING_RULES {
            assert!(
                rendered.contains(rule.task_shape),
                "row missing for task_shape `{}`",
                rule.task_shape
            );
        }
    }

    #[test]
    fn routing_policy_table_compiles_to_markdown_identical_to_checked_in_file() {
        // Phase P6-a round-trip contract: the snapshot at
        // `docs/routing-policy.md` must match the output of
        // `render_routing_policy_markdown()` byte-for-byte. If this
        // fails, regenerate with `cargo test -p codelens-mcp
        // regenerate_routing_policy_markdown -- --ignored`.
        let snapshot_path = routing_policy_snapshot_path();
        let expected = render_routing_policy_markdown();
        let actual = std::fs::read_to_string(&snapshot_path).unwrap_or_else(|err| {
            panic!(
                "failed to read routing policy snapshot at {}: {err}. \
                 Run `cargo test -p codelens-mcp regenerate_routing_policy_markdown -- --ignored` to create it.",
                snapshot_path.display()
            )
        });
        assert_eq!(
            actual, expected,
            "routing policy markdown drifted from the Rust source of truth; \
             regenerate via `cargo test -p codelens-mcp \
             regenerate_routing_policy_markdown -- --ignored`"
        );
    }

    #[test]
    #[ignore = "Regeneration helper — run explicitly via \
                `cargo test -p codelens-mcp regenerate_routing_policy_markdown -- --ignored` \
                after editing ROUTING_RULES. Writes the snapshot to docs/routing-policy.md."]
    fn regenerate_routing_policy_markdown() {
        let path = routing_policy_snapshot_path();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .unwrap_or_else(|err| panic!("failed to create {}: {err}", parent.display()));
        }
        std::fs::write(&path, render_routing_policy_markdown())
            .unwrap_or_else(|err| panic!("failed to write {}: {err}", path.display()));
    }

    #[test]
    fn eval_scenarios_battery_has_ten_entries_across_three_lanes() {
        // Phase P6-b slice 1: the plan specifies a 10-scenario
        // battery spanning every routing lane so the eval harness
        // can report per-lane metrics. Guard the count + lane
        // coverage so a future edit can't silently shrink the
        // battery.
        assert_eq!(
            EVAL_SCENARIOS.len(),
            10,
            "eval battery must hold exactly 10 scenarios; got {}",
            EVAL_SCENARIOS.len()
        );
        let labels: std::collections::BTreeSet<_> = EVAL_SCENARIOS
            .iter()
            .map(|scenario| scenario.expected_lane.as_label())
            .collect();
        assert!(labels.contains("native"), "missing native-lane scenarios");
        assert!(
            labels.contains("codelens_after_bootstrap"),
            "missing codelens-lane scenarios"
        );
        assert!(
            labels.contains("async_analysis"),
            "missing async-lane scenarios"
        );
    }

    #[test]
    fn eval_scenarios_json_round_trip_matches_checked_in_snapshot() {
        // Contract: the fixture at benchmarks/scenarios/extreme-efficiency.json
        // must equal `render_eval_scenarios_json()` byte-for-byte.
        // Regenerate via `cargo test -p codelens-mcp
        // regenerate_eval_scenarios_json -- --ignored`.
        let snapshot_path = eval_scenarios_snapshot_path();
        let expected = render_eval_scenarios_json();
        let actual = std::fs::read_to_string(&snapshot_path).unwrap_or_else(|err| {
            panic!(
                "failed to read scenarios snapshot at {}: {err}. \
                 Run `cargo test -p codelens-mcp \
                 regenerate_eval_scenarios_json -- --ignored` to create it.",
                snapshot_path.display()
            )
        });
        assert_eq!(
            actual, expected,
            "scenarios JSON drifted from EVAL_SCENARIOS; \
             regenerate via `cargo test -p codelens-mcp \
             regenerate_eval_scenarios_json -- --ignored`"
        );
    }

    #[test]
    #[ignore = "Regeneration helper — run explicitly via \
                `cargo test -p codelens-mcp regenerate_eval_scenarios_json -- --ignored` \
                after editing EVAL_SCENARIOS. Writes the snapshot to \
                benchmarks/scenarios/extreme-efficiency.json."]
    fn regenerate_eval_scenarios_json() {
        let path = eval_scenarios_snapshot_path();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .unwrap_or_else(|err| panic!("failed to create {}: {err}", parent.display()));
        }
        std::fs::write(&path, render_eval_scenarios_json())
            .unwrap_or_else(|err| panic!("failed to write {}: {err}", path.display()));
    }
}
