//! Phase P6-a — routing policy as code.
//!
//! The goal of Pillar 6 in `docs/plans/PLAN_extreme-efficiency.md` is
//! that the "CodeLens vs native" routing decision lives in code, not
//! in drift-prone markdown. This module declares the policy as a
//! typed table and emits a deterministic markdown rendering; the
//! checked-in snapshot at `docs/routing-policy.md` is generated from
//! this source of truth, and the integration test
//! `routing_policy_table_compiles_to_markdown_identical_to_checked_in_file`
//! guards round-trip equivalence.
//!
//! Scope for this slice: the declarative table + the generator +
//! the snapshot. The full evaluation harness that compares CodeLens
//! vs native vs hybrid on 10 synthetic tasks is Phase P6-b.

/// A routing rule: which task shape maps to which execution lane,
/// plus a short rationale sentence for the generated markdown.
#[derive(Clone, Copy, Debug)]
pub(crate) struct RoutingRule {
    pub task_shape: &'static str,
    pub lane: RoutingLane,
    pub rationale: &'static str,
}

/// The lane the harness should pick for a given task shape. Names
/// mirror the executor labels the CodeLens CLI already emits so the
/// generator can surface them without translation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum RoutingLane {
    Native,
    CodeLensAfterBootstrap,
    AsyncAnalysis,
}

impl RoutingLane {
    pub(crate) fn as_label(&self) -> &'static str {
        match self {
            RoutingLane::Native => "native",
            RoutingLane::CodeLensAfterBootstrap => "codelens_after_bootstrap",
            RoutingLane::AsyncAnalysis => "async_analysis",
        }
    }
}

/// The declarative routing table. Ordered deterministically so the
/// generated markdown is stable byte-for-byte across runs.
pub(crate) const ROUTING_RULES: &[RoutingRule] = &[
    RoutingRule {
        task_shape: "simple local lookup / single-file edit (<30 LOC)",
        lane: RoutingLane::Native,
        rationale: "Native Read/Grep is faster and bypasses CodeLens warm-up cost.",
    },
    RoutingRule {
        task_shape: "multi-file review or impact analysis",
        lane: RoutingLane::CodeLensAfterBootstrap,
        rationale: "Switch to CodeLens workflow tools after the first concrete local step for bounded blast-radius reports.",
    },
    RoutingRule {
        task_shape: "refactor preflight (rename / extract / move)",
        lane: RoutingLane::CodeLensAfterBootstrap,
        rationale: "Use verify_change_readiness + safe_rename_report before mutation tools.",
    },
    RoutingRule {
        task_shape: "onboarding / planning an unfamiliar repo",
        lane: RoutingLane::CodeLensAfterBootstrap,
        rationale: "onboard_project + get_ranked_context give better context-per-token than ad-hoc grep.",
    },
    RoutingRule {
        task_shape: "long-running analysis (dead_code, module_boundary)",
        lane: RoutingLane::AsyncAnalysis,
        rationale: "Use start_analysis_job + poll, not synchronous workflow tools; avoids blocking the session.",
    },
];

/// Render the routing table as markdown. The format is intentionally
/// minimal so the round-trip snapshot test is easy to read and
/// mechanical to regenerate.
pub(crate) fn render_routing_policy_markdown() -> String {
    let mut out = String::new();
    out.push_str("<!-- Generated by codelens-mcp::routing_policy::render_routing_policy_markdown. DO NOT EDIT BY HAND. -->\n");
    out.push_str("# CodeLens Routing Policy\n\n");
    out.push_str(
        "Authoritative routing table, kept in sync with `crates/codelens-mcp/src/routing_policy.rs`. \
         Regenerate via `cargo test -p codelens-mcp routing_policy` when the Rust table changes.\n\n",
    );
    out.push_str("| Task shape | Lane | Rationale |\n");
    out.push_str("| --- | --- | --- |\n");
    for rule in ROUTING_RULES {
        out.push_str(&format!(
            "| {} | `{}` | {} |\n",
            rule.task_shape,
            rule.lane.as_label(),
            rule.rationale,
        ));
    }
    out
}

/// Path of the checked-in markdown snapshot, relative to the repo root.
pub(crate) const ROUTING_POLICY_SNAPSHOT_PATH: &str = "docs/routing-policy.md";

/// Absolute path to the snapshot, resolved via `CARGO_MANIFEST_DIR`
/// so the round-trip test works from any cwd.
pub(crate) fn routing_policy_snapshot_path() -> std::path::PathBuf {
    let manifest = env!("CARGO_MANIFEST_DIR");
    std::path::Path::new(manifest)
        .parent()
        .and_then(|p| p.parent())
        .expect("CARGO_MANIFEST_DIR must have a repo-root ancestor")
        .join(ROUTING_POLICY_SNAPSHOT_PATH)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_lane_is_represented_in_the_table() {
        // Keeps the table from silently dropping a lane when a rule
        // is edited. If a new lane variant is added, at least one
        // rule must reference it so the markdown stays informative.
        let labels: std::collections::BTreeSet<_> = ROUTING_RULES
            .iter()
            .map(|rule| rule.lane.as_label())
            .collect();
        assert!(labels.contains("native"));
        assert!(labels.contains("codelens_after_bootstrap"));
        assert!(labels.contains("async_analysis"));
    }

    #[test]
    fn rendered_markdown_includes_header_and_row_per_rule() {
        let rendered = render_routing_policy_markdown();
        assert!(rendered.starts_with("<!-- Generated by"));
        assert!(rendered.contains("| Task shape | Lane | Rationale |"));
        for rule in ROUTING_RULES {
            assert!(
                rendered.contains(rule.task_shape),
                "row missing for task_shape `{}`",
                rule.task_shape
            );
        }
    }

    #[test]
    fn routing_policy_table_compiles_to_markdown_identical_to_checked_in_file() {
        // Phase P6-a round-trip contract: the snapshot at
        // `docs/routing-policy.md` must match the output of
        // `render_routing_policy_markdown()` byte-for-byte. If this
        // fails, regenerate with `cargo test -p codelens-mcp
        // regenerate_routing_policy_markdown -- --ignored`.
        let snapshot_path = routing_policy_snapshot_path();
        let expected = render_routing_policy_markdown();
        let actual = std::fs::read_to_string(&snapshot_path).unwrap_or_else(|err| {
            panic!(
                "failed to read routing policy snapshot at {}: {err}. \
                 Run `cargo test -p codelens-mcp regenerate_routing_policy_markdown -- --ignored` to create it.",
                snapshot_path.display()
            )
        });
        assert_eq!(
            actual, expected,
            "routing policy markdown drifted from the Rust source of truth; \
             regenerate via `cargo test -p codelens-mcp \
             regenerate_routing_policy_markdown -- --ignored`"
        );
    }

    #[test]
    #[ignore = "Regeneration helper — run explicitly via \
                `cargo test -p codelens-mcp regenerate_routing_policy_markdown -- --ignored` \
                after editing ROUTING_RULES. Writes the snapshot to docs/routing-policy.md."]
    fn regenerate_routing_policy_markdown() {
        let path = routing_policy_snapshot_path();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .unwrap_or_else(|err| panic!("failed to create {}: {err}", parent.display()));
        }
        std::fs::write(&path, render_routing_policy_markdown())
            .unwrap_or_else(|err| panic!("failed to write {}: {err}", path.display()));
    }
}
